### ISSUE TITLE
refs not rendered

### ISSUE THREAD

**Issue by arielgabizon** [0xPolygonHermez/zkevm-techdocs#39]
In https://github.com/0xPolygonHermez/zkevm-techdocs/blob/main/docs/proof-recursion/v.1.1/proof-recursion.pdf
the bibliography refs appear as [?]
e.g.
![image](https://github.com/0xPolygonHermez/zkevm-techdocs/assets/5689834/60ca36fa-e150-4e27-b7fe-d13d73815d97)

**Comment by marcguzmanalbiol** [comment]
Solved for this particular document.
